# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/rhode/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rhode)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,c3f0a30e7e5d0d20a819875d0e30c475471792cd)
$(call add-radio-file-sha1-checked,radio/modem.img,50ed3d334047296db405d5b0d173bf47ed533a5d)
$(call add-radio-file-sha1-checked,radio/abl.img,e9061e3d04b2d4ec07fd41a04ef2c3b82341d1ea)
$(call add-radio-file-sha1-checked,radio/devcfg.img,3638abd212aba8be39af85c1277a32013b29852a)
$(call add-radio-file-sha1-checked,radio/dsp.img,a6eccd278e8409e05337ffd6c11e593e8e2944a5)
$(call add-radio-file-sha1-checked,radio/fsg.img,d04cc1fb24f1a9ed9826a7790c3b4298621f30a4)
$(call add-radio-file-sha1-checked,radio/hyp.img,5335981894a8468fc9108de491b6cf8b8fc9b837)
$(call add-radio-file-sha1-checked,radio/keymaster.img,f72e4c006cf7994720fcf9b9654348146edf3074)
$(call add-radio-file-sha1-checked,radio/logo.img,dd619079a670eb1508da860b1b16bdb9af7c0a25)
$(call add-radio-file-sha1-checked,radio/prov.img,b4aa2904ae189df4a97ed4759cd9ff37dc74be77)
$(call add-radio-file-sha1-checked,radio/qupfw.img,be053716e3356c4c2d46766b5ddbcd54969e86aa)
$(call add-radio-file-sha1-checked,radio/rpm.img,a53b91837423f489d1927417fd16f097033d0646)
$(call add-radio-file-sha1-checked,radio/storsec.img,c02eac481ea5393efe7c8827209e6916fee6478a)
$(call add-radio-file-sha1-checked,radio/tz.img,98584c128237f71a251c838b35a44071a5715f21)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,a27df545bfe8af6b45dab7f438e43c1879dc0eeb)
$(call add-radio-file-sha1-checked,radio/xbl.img,fc76ea0262334c4f5f20dfaef7821b9a0bc29ea4)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,5f2a6edb9a059aee66d46bd3ca67ce2c53c22694)

endif
